/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import javafx.scene.paint.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    int turn=2;
    int buttonused[]={0,0,0,0,0,0,0,0,0};
    int p1won[]={0,0,0,0,0,0,0,0,0};
    int p2won[]={0,0,0,0,0,0,0,0,0};

    private NewJFrame1(String manisha_Tic_Tac_Toe_) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    int p1won()
    {
        if(p1won[0]==1 && p1won[1]==1 && p1won[2]==1)
        {
            return 1;
        }
        if(p1won[3]==1 && p1won[4]==1 && p1won[5]==1)
        {
            return 1;
        }
        if(p1won[6]==1 && p1won[7]==1 && p1won[8]==1)
        {
            return 1;
        }
        if(p1won[0]==1 && p1won[3]==1 && p1won[6]==1)
        {
            return 1;
        }
        
        if(p1won[1]==1 && p1won[4]==1 && p1won[7]==1)
        {
            return 1;
        }
    
        if(p1won[2]==1 && p1won[5]==1 && p1won[8]==1)
        {
            return 1;
        }
        
        if(p1won[2]==1 && p1won[4]==1 && p1won[6]==1)
        {
            return 1;
        }
    
        if(p1won[0]==1 && p1won[4]==1 && p1won[8]==1)
        {
            return 1;
        }
        else 
            return 0;
    }
    int p2won()
    {
        if(p2won[0]==1 && p2won[1]==1 && p2won[2]==1)
        {
            return 1;
        }
        if(p2won[3]==1 && p2won[4]==1 && p2won[5]==1)
        {
            return 1;
        }
        if(p2won[6]==1 && p2won[7]==1 && p2won[8]==1)
        {
            return 1;
        }
        if(p2won[0]==1 && p2won[3]==1 && p2won[6]==1)
        {
            return 1;
        }
        
        if(p2won[1]==1 && p2won[4]==1 && p2won[7]==1)
        {
            return 1;
        }
    
        if(p2won[2]==1 && p2won[5]==1 && p2won[8]==1)
        {
            return 1;
        }
        
        if(p2won[2]==1 && p2won[4]==1 && p2won[6]==1)
        {
            return 1;
        }
    
        if(p2won[0]==1 && p2won[4]==1 && p2won[8]==1)
        {
            return 1;
        }
        else 
            return 0;
    }
    



    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b9 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\images.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 51, 255));
        getContentPane().setLayout(null);

        b9.setBackground(new java.awt.Color(255, 204, 204));
        b9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(260, 180, 90, 54);

        b5.setBackground(new java.awt.Color(255, 204, 204));
        b5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(160, 120, 90, 54);

        b6.setBackground(new java.awt.Color(255, 204, 204));
        b6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(260, 120, 90, 54);

        b7.setBackground(new java.awt.Color(255, 204, 204));
        b7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b7.setText(" ");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(60, 180, 90, 54);

        b8.setBackground(new java.awt.Color(255, 204, 204));
        b8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(160, 180, 90, 54);

        b1.setBackground(new java.awt.Color(255, 204, 204));
        b1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(60, 60, 90, 54);

        b2.setBackground(new java.awt.Color(255, 204, 204));
        b2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(160, 60, 90, 54);

        b4.setBackground(new java.awt.Color(255, 204, 204));
        b4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(60, 120, 90, 54);

        b3.setBackground(new java.awt.Color(255, 204, 204));
        b3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(260, 60, 90, 54);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Play Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 260, 150, 47);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\images (1).jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 410, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           b1.setText("");
              b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
         b8.setText("");
        b9.setText("");

        turn =2;
        for(int i=0;i<9;i++)
        {
            buttonused[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            p1won[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            p2won[i]=0;
        }

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
         if(buttonused[0]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b1.setText("X");
                                

                buttonused[0]=1;
                p1won[0]=1;
                int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
            }
            else
            {
                turn++;
                b1.setText("O");
                
                buttonused[0]=1;
                p2won[0]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }
    
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
          if(buttonused[1]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b2.setText("X");
                buttonused[1]=1;
                p1won[1]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
                
            }
            else
            {
                turn++;
                b2.setText("O");
                buttonused[1]=1;
                p2won[1]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
          if(buttonused[2]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b3.setText("X");
                buttonused[2]=1;
                p1won[2]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
            }
            else
            {
                turn++;
                b3.setText("O");
                buttonused[2]=1;
                p2won[2]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(buttonused[3]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b4.setText("X");
                buttonused[3]=1;
                p1won[3]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
                
            }
            else
            {
                turn++;
                b4.setText("O");
                buttonused[3]=1;
                p2won[3]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
          if(buttonused[4]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b5.setText("X");
                buttonused[4]=1;
                p1won[4]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
                
            }
            else
            {
                turn++;
                b5.setText("O");
                buttonused[4]=1;
                p2won[4]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
         if(buttonused[5]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b6.setText("X");
                buttonused[5]=1;
                p1won[5]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
            else
            {
                turn++;
                b6.setText("O");
                buttonused[5]=1;
                p2won[5]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         if(buttonused[6]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b7.setText("X");
                buttonused[6]=1;
                p1won[6]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
            else
            {
                turn++;
                b7.setText("O");
                buttonused[6]=1;
                p2won[6]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
         if(buttonused[7]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b8.setText("X");
                buttonused[7]=1;
                p1won[7]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }

            }
            else
            {
                turn++;
                b8.setText("O");
                buttonused[7]=1;
                p2won[7]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
         if(buttonused[8]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b9.setText("X");
                buttonused[8]=1;
                p1won[8]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
            else
            {
                turn++;
                b9.setText("O");
                buttonused[8]=1;
                p2won[8]=1;
                 int result1=p1won();
                int result2=p2won();
                if(result1==1)
                {
                   JOptionPane.showMessageDialog(rootPane,"Player1 has won");

                }
                else if(result2==1)
                {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has won");

                }
               
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Warning:This is already used");
        }

    }//GEN-LAST:event_b9ActionPerformed

    /**
     * @param args the command line arguments
     */                                 
        // TODO add your handling code here:
                                       
    // TODO add your handling code here:
             
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
